version: '3.8'

services:
  frontend:
    build:
      context: .
    ports:
      - "4200:4200"
    networks:
      - app-network
    volumes:
      - ./src:/app/src
      - /app/node_modules

  backend:
    build:
      context: ../car-price-compare-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/precificar
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      JWT_SECRET: BboUQ8xAZoO6iLizC9FK1XgNhVhA+UeB4AlQ6GNrrLA==

  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: precificar
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
